### ISSUE TITLE
Issue with the excel file

### ISSUE THREAD

**Issue by HamzaOuajhain** [RuifMaxx/Multidimensional-time-series-with-transformer#3]
Would you be able to download the file and upload it in Mega instead of baidu, because if you don't have a chinese number you won't be able to download it.

Thanks a lot

**Comment by RuifMaxx** [comment]
OK，I will fix it



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 17, 2023 02:57 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [RuifMaxx/Multidimensional-time-series-with-transformer] Issue withthe excel file (Issue #3)




 
Would you be able to download the file and upload it in Mega instead of baidu, because if you don't have a chinese phone you won't be able to download it.
 
Thanks a lot

**Comment by HamzaOuajhain** [comment]
and also update the ReadMe file so other can see it, you can use Mega for example to host your file.

**Comment by HamzaOuajhain** [comment]
Can you post the link in the Read Me so eveyone can have access to the excel file used.

**Comment by RuifMaxx** [comment]
> Can you post the link in the Read Me so eveyone can have access to the excel file used.

https://docs.google.com/spreadsheets/d/1P8nIB2Ugd9AMcGlAPu3lD2yh2eAyJVh3/edit?usp=drive_link&ouid=102877252444231070619&rtpof=true&sd=true

or 

https://drive.google.com/file/d/13FyJqP_MVVHzqQ3G0egpglelO0G-dsEa/view?usp=drive_link

**Comment by HamzaOuajhain** [comment]
Thank you !
